spring:
  application:
    name: check-card

  data:
    mongodb:
      uri: "mongodb://checkCardAdmin:Fulbert05@localhost:27017/checkCard?authSource=checkCard"
      #database: checkCard

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tresodev@gmail.com}
    password: ${MAIL_PASSWORD:jzzvoabugaqffgta}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret: ${JWT_SECRET:Kj83#kS!9dP2$Ls8Qp1@xZ4vN7mR6tY5bH3cD0eF}
      expiration-ms: 3600000

server:
  port: 8080
